- config/custom-environment-variables.yaml
bug fix in postcode configuration
> bug fix in postcode configuration

- test/end-to-end/paths/logout.js
https://tools.hmcts.net/jira/browse/DIV-2000
End to end test added.
> DIV-2000-Logout

- app/steps/pay/pay-online-only/index.js
- app/steps/pay/pay-online-only/index.test.js
Use the correct payment code and amount when making payment
> Fix payment

- app/middleware/updateApplicationFeeMiddleware.js
[DIV-2256 - SONARQUBE: 1 bugs found in sonarqube for frontend](https://tools.hmcts.net/jira/browse/DIV-2256)
SonarQube has found a bug in updateApplicationFeeMiddleware.js:
> `"getFeeFromService"` declared at line 25 expects 0 arguments, but 1 was provided`
> remove un-required argument for function

- app/steps/authenticated/index.js
Authentication page returning error as result of https://github.com/hmcts/div-petitioner-frontend/pull/19
> fix auth page

- test/end-to-end/pages/pay/by-card-online-on-govpay.js
- test/end-to-end/pages/pay/pay-online-only.js
- test/end-to-end/paths/payment.js
These extra tests are to ensure that our integration with Fees Register are working as expected in our integrated environments.
Relates to DIV-1986.
This has been verified both locally and via Continuous Integration pipeline.
* Hardware: CI Box
* O/S and version: Jenkins
* JDK:
> Adding fees tests to e2e to ensure integrations work in environments

- app/steps/timeout/content.json
- app/steps/timeout/template.html
Updated the timeout page content after the user click 'Save and Close'
> Update timeout page for save and close

- app/middleware/updateApplicationFeeMiddleware.js
- config/custom-environment-variables.yaml
- config/default.yaml
This change is to make sure that the real Fees endpoint is integrated with in all test environments (other than during development on a local environment). 
Fixes # DIV-1976
This has been tested both manually and automatically on local machine.
* Hardware: Mac
* O/S and version: OSX
* JDK:
> @DIV-1976: fix to only use Fees stub on local environment

- app/steps/marriage/certificate-names/content.json
- app/steps/marriage/certificate-names/index.test.js
- app/steps/marriage/certificate-names/template.html
Conditional content added for name change step
* Hardware:
* JDK:
> Condditional content added for name change step

- app/steps/pay/pay-online-only/content.json
- app/steps/pay/pay-online-only/template.html
Added a line about paying within 60 minutes.
> Urgent content fix with payment warning.

- app/steps/pay/card-payment-status/index.js
- app/steps/pay/pay-online-only/index.js
- app/steps/pay/pay-online-only/index.test.js
Changed the payment amount to be in pound sterling and the redirect url to be the `/done-and-submitted` page
> Changed the page the payment is ending on

- app/services/payment.js
- app/services/payment.test.js
> Div 2098 fix ccd update

- app/steps/pay/card-payment-status/index.test.js
> Fix failing unit tests due to case sensitivity

- app/services/mocks/payment.js
- app/services/submission.js
* Updated the code that parses the date before sending it to CCD. 
* Noticed that CCD has the wrong payment amount as well. Updated the amount to be in pence
Fixes # [DIV-2345 Wrong payment date sent to CCD](https://tools.hmcts.net/jira/browse/DIV-2345)
Tested on Dev A
> Wrond payment date is sent to CCD

- app/steps/grounds-for-divorce/adultery/3rd-party/details/schema.json
- app/steps/marriage/certificate-names/index.test.js
- app/steps/marriage/certificate-names/schema.json
- app/steps/marriage/names/index.test.js
- app/steps/marriage/names/schema.json
[DIV-2283 - Remove field validation](https://tools.hmcts.net/jira/browse/DIV-2283)
Removing strict validation for string inputs
Manually
> removed strict string validation

- app/services/payment.js
- app/services/payment.test.js
> Div 2397 payment reference not being included with successful payment master

- app/steps/check-your-answers/index.test.js
- app/steps/check-your-answers/template.html
> DIV-2084-Accessibility-Header-must-not-be-empty

- app/services/payment.js
- app/services/payment.test.js
https://tools.hmcts.net/jira/browse/DIV-2397
> Div 2397 payment reference not being included with successful payment

- app/assets/javascripts/documentUpload.js
- app/steps/marriage/upload/template.html
[DIV-2278 - DIV-Accessibility- Java Script- petitioner-respondent/address pages (A)](https://tools.hmcts.net/jira/browse/DIV-2278)
Removes custom tab order and prevent double trigger of upload modal
Manually tested.
> Fix focus issue on document upload, add browser detection functionality

- app/steps/done-and-submitted/content.json
- app/steps/done-and-submitted/index.test.js
- app/steps/done-and-submitted/template.html
[DIV-2305 - Change payment content on done screen](https://tools.hmcts.net/jira/browse/DIV-2305)
Update copy and UI in accordance with jira ticket
Manually and unit tests
> Change payment content on done screen

- app/assets/sass/_dropzone.scss
[DIV-2411 - DIV- Accessibility - File Upload Progress Bar Contrast (AAA)](https://tools.hmcts.net/jira/browse/DIV-2411)
To fix the issue I have increased the contrast of the upload progress bar
Visually
> increase upload progress contrast

- app/core/handler/runStepHandler.js
- app/middleware/draftPetitionStoreMiddleware.js
- app/middleware/draftPetitionStoreMiddleware.test.js
- app/resources/sessionBlacklistedAttributes.json
- app/services/mocks/transformationServiceClient.js
- app/steps/submit/index.js
This has already been merged and tested in develop.
> Draftstore restore bug

- infrastructure/demo.tfvars
- infrastructure/main.tf
Force https for frontend in CNP
> Force https

- app/services/healthcheck.js
- infrastructure/demo.tfvars
- infrastructure/prod.tfvars
- package.json
www is required for public facing site urls.
> Use www for additional host names

- app/services/healthcheck.js
- app/steps/index/content.json
- app/steps/index/template.html
- config/default.yaml
- infrastructure/prod.tfvars
- test/end-to-end/pages/index/index.js
- test/end-to-end/paths/payment.js
- test/end-to-end/smoke/smoketest.js
Changes include:
Healthcheck timeout increase from 2 to 5 seconds. https://tools.hmcts.net/jira/browse/DIV-2610
Content change for the index page and associated test fixes: https://tools.hmcts.net/jira/browse/DIV-2602
External hostname for frontend on production: https://tools.hmcts.net/jira/browse/DIV-2560
> !DO NOT MERGE - Until Monday Release Window! Merge Demo to Master

- infrastructure/main.tf
Changed the configuration to allow http requests.
* Hardware:
* JDK:
> Allow http requests

- bin/run-functional-tests.sh
- docker/test-compose.yaml
- package.json
- test/end-to-end/helpers/JSWait.js
- test/end-to-end/pages/index/index.js
- test/end-to-end/pages/marriage/upload.js
- test/end-to-end/paths/aboutYourMarriageCertificate.js
- test/end-to-end/paths/cookieBanner.js
- test/end-to-end/paths/errorPaths.js
- test/end-to-end/paths/foreignMarriageCertificates.js
- test/end-to-end/paths/invalidCsrf.js
- test/end-to-end/paths/jurisdictionConnections.js
- test/end-to-end/paths/livingTogether.js
- test/end-to-end/paths/logout.js
- test/end-to-end/paths/payment.js
- test/end-to-end/paths/postcode.js
- test/end-to-end/paths/reasonsForDivorce.js
- test/end-to-end/paths/reportAProblemPath.js
- test/end-to-end/paths/save-resume.js
- test/end-to-end/paths/startSession.js
- test/end-to-end/paths/staticPages.js
- test/end-to-end/paths/uploadMarriageCertificate.js
- yarn.lock
This change adds the `@overnight` tag to several tests that don't need to be run as part of every build in the pipeline, but instead are suitable to run as part of the overnight test pack. Tests that are eligible for being pulled out of the pipeline are low-traffic paths and/or paths that have a lot of coverage elsewhere by other e2e and unit level tests (e.g. some of the more obscure jurisdiction scenarios).
A new e2e payment test has been added that covers both routes (cancellation, failure) that was previously done by separate tests, which should speed them up.
Have allowed all tests 1 retry to cope with unknown flakiness in the preview build pipeline (which follows what we would do manually anyway) - once the stability of the pipelines are further improved we can look to remove these …
> Make some e2e tests only run in the overnight pack

- .nsprc
- app/services/mocks/feeRegisterService.js
- app/steps/pay/pay-online-only/index.test.js
- config/default.yaml
Changed the fee code to use the new fee code. A proper solution  to lookup the fee code is required
> Changed the fee code

- Jenkinsfile_CNP
- app/components/AddressLookupStep/template.html
- app/steps/done-and-submitted/template.html
- app/steps/grounds-for-divorce/unreasonable-behaviour/template.html
- app/steps/jurisdiction/domicile/content.json
- app/steps/jurisdiction/domicile/template.html
- app/steps/jurisdiction/last-habitual-residence/template.html
- app/steps/marriage/upload/template.html
- app/steps/petitioner/changed-name/template.html
- app/steps/terms-and-conditions/content.json
- app/views/common/address/enter-abroad.html
- app/views/common/components/formElements.html
- test/validation/htmlTest.js
Fixes # DIV-1085
Manually tested.
Automatically tested - unit tests, e2e tests.
> W3c HTML validation test

- config/default.yaml
- infrastructure/variables.tf
Update court weight values to receive an equal weighting
Fixes # DIV-2708
> Update court weight values to receive an equal weighting

- infrastructure/main.tf
- infrastructure/output.tf
Get it working on Preview environment
* Hardware:
* JDK:
> clean up of vault creation code

- app/steps/pay/pay-online-only/content.json
- app/steps/pay/pay-online-only/template.html
Urgent content about refunds for publishing asap.
> Adding content about refunds. Changing content about saving.

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
Based off the Redis CNP setup done in the div-frontend-boilerplate. To test if this fixes demo env. Proper PR will be required for AAT -> master build.
> use CNP RedisCloud URL

- app/steps/check-your-answers/index.js
- app/steps/check-your-answers/index.test.js
Fix bug where court allocation was removed from the submission step.
Manual and units
> add court allocation back into the build

- app/filters/nunjucks.js
- app/filters/nunjucks.test.js
- app/steps/done-and-submitted/template.html
[DIV-2412 - DIV- Accessibility -Case Number Format- page (AAA)](https://tools.hmcts.net/jira/browse/DIV-2412)
Change the - to a unicode value so the screen reader will pick up its correct meaning
Manually using a screen reader
> change dash to unicode value

- app/steps/done-and-submitted/content.json
Changing  "Contact the divorce centre if you don't hear anything back after 2 weeks."
to
"Contact the divorce centre if you don't hear anything back after 3 weeks."
> Urgent content fix

- app/steps/grounds-for-divorce/unreasonable-behaviour/index.js
- app/steps/grounds-for-divorce/unreasonable-behaviour/index.test.js
[Seeing unreasonable behaviour default values in CCD](https://tools.hmcts.net/jira/browse/DIV-2798)
Fix bug where default values were being shown in CCD
Unit tests and manual
> filter posted data on parsing data from request

- infrastructure/variables.tf
RDC Allocation Change,
EMDU- 20%
Southampton- 20%
Liverpool-25%
Stoke- 35%
* Hardware:
* JDK:
> [PREVIEW] change RDC allocation

- app/steps/petitioner/changed-name/content.json
Updating this question to simplify and bring into line with prototype.
> [PREVIEW] Updating question to simplify and mirror prototype

- app/services/jurisdiction/connections.js
Remove dead code that make sonar quality gate fails.
> [PREVIEW] Remove dead code that make sonar fails

- infrastructure/main.tf
master build is failing for some vault unsupported protocol issue. This PR is to try to resolve it.
> Cleaned up local vault naming

- bin/run-crossbrowser-tests-local.sh
- config/default.yaml
- test/crossbrowser/supportedBrowsers.js
DIV-3010 Update tunnel name, test on one browser for nightly cross browser testing
> DIV-3010-update tunnel name

- test/end-to-end/helpers/SauceLabsReportingHelper.js
- test/end-to-end/paths/basicDivorce.js
To clear error in Jenkins is : The Sauce OnDemand plugin is configured, but no session IDs were found in the test output.
> Add session to archive reports in jenkins

- infrastructure/prod.tfvars
Change Idam prod url
* Hardware:
* JDK:
> Update Idam urls

- Jenkinsfile_nightly
Enable mutation on nightly pipeline
> enable mutation

- infrastructure/main.tf
- infrastructure/variables.tf
User shared ASP Preview
User shared ASP Preview
* Hardware:
* JDK:
> [PREVIEW] User shared ASP Preview

- app/middleware/draftPetitionStoreMiddleware.js
- app/middleware/draftPetitionStoreMiddleware.test.js
- app/steps/check-your-answers/index.js
- app/steps/grounds-for-divorce/reason/index.js
- infrastructure/main.tf
- infrastructure/variables.tf
> Keep Demo Up to Date

- app/steps/grounds-for-divorce/unreasonable-behaviour/content.json
- app/steps/grounds-for-divorce/unreasonable-behaviour/template.html
Updating the content with content produced for Decree nisi stage.
> Update the content in preparation for the Decree nisi

- infrastructure/error_service.tf
- infrastructure/error_service_action_group.tf
- infrastructure/main.tf
- infrastructure/variables.tf
Set resource group for appInsight alert
Set resource group for appInsight alert
* Hardware:
* JDK:
> [PREVIEW] Fix rss group for alerts

- app/steps/grounds-for-divorce/reason/index.js
- app/steps/grounds-for-divorce/reason/index.test.js
- app/steps/grounds-for-divorce/respondent-consent/content.json
- app/steps/grounds-for-divorce/respondent-consent/index.js
- app/steps/grounds-for-divorce/respondent-consent/index.test.js
- app/steps/grounds-for-divorce/respondent-consent/schema.json
- app/steps/grounds-for-divorce/respondent-consent/template.html
- test/end-to-end/pages/grounds-for-divorce/respondent-consent.js
- test/end-to-end/paths/reasonsForDivorce.js
> Latest master to demo

- app/steps/screening-questions/has-marriage-broken/template.html
- app/steps/screening-questions/has-marriage-cert/template.html
- app/steps/screening-questions/has-respondent-address/template.html
Remove save and close from all screening questions
* Hardware:
* JDK:
> remove save and close from all screening questions

- app/steps/grounds-for-divorce/reason/index.js
- app/steps/grounds-for-divorce/reason/index.test.js
- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
- test/end-to-end/paths/reasonsForDivorce.js
Only show respondent consent if feature flag is active.
[DIV-3609 - Toggle off DN front loaded questions](https://tools.hmcts.net/jira/browse/DIV-3609)
> only show respondent consent if feature flag is active

- infrastructure/output.tf
Add missing output variable which causing functionality to persist on live still
[DIV-3609 - Toggle off DN front loaded questions](https://tools.hmcts.net/jira/browse/DIV-3609)
> Add missing output variable which causing functionality to persist on live still

- test/end-to-end/codecept.conf.js
Reducing to 4 to see if it helps.
> One thread when using 5 seems to always get stuck.

- app/steps/grounds-for-divorce/reason/index.js
Fix way boolean is passed for feature flag respondentConsent
> Fix way boolean is passed for feature flag respondentConsent

- infrastructure/variables.tf
> court changes

- sonar-project.properties
> Temporarily disable healthcheck sonar coverage

- .nsprc
- package.json
- yarn.lock
Updated dependencies to remove all critical & moderate vulnerabilities whilst significantly reducing the number of low as well. 
From:
_34 vulnerabilities found
Severity: 17 Low | 16 Moderate | 1 Critical_
To:
_2 vulnerabilities found
Severity: 2 Low_
> [PREVIEW] Update dependencies to reduce vulnerabilities

- app/core/helpers/staleDataManager.js
- app/steps/financial/arrangements/index.js
Fixing typos
* Hardware:
* JDK:
> Fixing typos

- app/core/fixtures/content/simple.json
- app/core/fixtures/schemas/simple.json
- app/core/steps/ValidationStep.js
- app/core/steps/ValidationStep.test.js
- package.json
- yarn.lock
This fixes a bug where an empty string is being accepted for required values (e.g petitioner first name/last name)
This happens when a Save and Resume occurs while on an incomplete form, where validation rules are not checked at the time
Fixes #DIV-3469
> DIV-3469 - filter out empty values before schema validation

- app/steps/check-your-answers/index.js
> DIV-3951 - log error message on submission failure

- infrastructure/prod.tfvars
> DIV-3930 - set DN production URL

- app/core/steps/DestroySessionStep.js
- app/core/steps/DestroySessionStep.test.js
- app/middleware/idamProtectMiddleware.js
- app/services/submission.js
- app/steps/authenticated/index.js
- app/steps/check-your-answers/index.js
- app/steps/pay/card-payment-status/paymentStatusService.js
- app/steps/pay/pay-online-only/index.js
- app/steps/start/index.js
- test/end-to-end/helpers/idamHelper.js
- test/end-to-end/pages/index/index.js
- test/end-to-end/pages/petitioner/contact-details.js
- test/end-to-end/paths/logout.js
- test/end-to-end/paths/reasonsForDivorce.js
- test/end-to-end/paths/save-resume.js
- test/mocks/idam.js
> parseBool all featureToggles

- Jenkinsfile_nightly
- test/security.sh
> set up divorce app security scan

- app/steps/pay/card-payment-status/paymentStatusService.js
- app/steps/pay/pay-online-only/index.js
- test/end-to-end/pages/address/postcode.js
Possibly fixes payment failing functional tests.
> Fix payment update code

- test/end-to-end/paths/save-resume.js
> Fixed Draft Store Tests now that Screening questions do not save draft

- test/end-to-end/paths/reasonsForDivorce.js
fixed test behind ft, parsebool() was missing
* Hardware:
* JDK:
> DIV-3964 fixing test behind feature toggle

- app/steps/grounds-for-divorce/adultery/details/index.test.js
- test/end-to-end/pages/grounds-for-divorce/adultery-details.js
- test/end-to-end/paths/reasonsForDivorce.js
> Div 3964 putting test behind feature toggle

- app/steps/pay/pay-online-only/content.json
- app/steps/pay/pay-online-only/index.js
- app/steps/pay/pay-online-only/index.test.js
Fee details should be dynamic in /pay/online section where payment will be processed
> Fee amount update in pay online screen

- .dockerignore
- .eslintignore
- Dockerfile
- acb.tpl.yaml
- kubernetes/deployment.template.yaml
- package.json
This PR leverages on layers re-use to reduce the the docker image build time in CI.
Jira ticket: https://tools.hmcts.net/jira/browse/CNP-1131
The PR CI shows a decrease of build time of the docker image (gain of 2:30 min ~ish).
> Activate ACR build, image multistaging and hmcts runtime user

- test/end-to-end/paths/reasonsForDivorce.js
PFE Master failure because of missing functional test check on desertion
> PFE Desertion functional test failure

- test/end-to-end/paths/reasonsForDivorce.js
> PFE functional test failure

- app/steps/grounds-for-divorce/desertion/when-left/index.js
- app/steps/grounds-for-divorce/desertion/when-left/index.test.js
- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/preview.tfvars
- infrastructure/variables.tf
- kubernetes/config.aat.yaml
[DIV-4342 - wrap changes in DIV-3981 in desertion feature toggle](https://tools.hmcts.net/jira/browse/DIV-4342)
- Created new feature toggle and wrapped desertion specific changes from DIV-4342 in it
> [PREVIEW] wrap changes from DIV-4342 in new desertion feature toggle

- app/views/common/components/formElements.html
- app/views/common/components/formElements.test.js
Fixing date input field validation
Fixes https://tools.hmcts.net/jira/browse/DIV-836
> DIV-836 Fixing date validation input

- package.json
- test/end-to-end/codecept.conf.js
- test/end-to-end/paths/basicDivorce.js
- yarn.lock
After removal of index page on nightly pipeline webdriverIO have an issue with index page. So just removed index and upgraded library
> Upgrade e2e test library

- test/end-to-end/paths/errorPaths.js
Previous version
https://github.com/hmcts/div-petitioner-frontend/commit/eb3759496bb83e3d6587ca6a89e274b2323f4767#diff-9056424dc26cb7dbac45da6f065724a6L27
It's no longer relevant as that feature flag is gone
Fixes # DIV-4469
> DIV-4469 - remove feature flag test

- test/end-to-end/paths/reasonsForDivorce.js
Fix failing e2e test that is causing master build to fail
> DIV-4364: Replace incorrect feature toggle in e2e tests

- app/steps/grounds-for-divorce/reason/index.js
- app/steps/grounds-for-divorce/reason/index.test.js
- app/steps/grounds-for-divorce/respondent-consent/index.js
- app/steps/grounds-for-divorce/respondent-consent/index.test.js
- config/custom-environment-variables.yaml
- config/default.yaml
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/preview.tfvars
- infrastructure/variables.tf
- test/end-to-end/paths/reasonsForDivorce.js
Fix broken feature toggles and failing e2e tests on master pipeline
> DIV-4562: Added 5.3.0 toggle to fix wrong page being shown

- app.js
- app/views/layout.html
Insert tracking image for detecting users with disabled javascript
Fixes #  DIV-4169
Tested Locally
> Phase one for tracking non javascript users

- infrastructure/variables.tf
> Update SiteID to A007 for CTSC

- config/default.yaml
- config/preview.yaml
- config/testing.yaml
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DIV-4669
Enable release520 flag by default (AKA release 5.3.0)
Please do not merge until release day
* Hardware:
* JDK:
> DIV-4669 Enable release520

- bin/run-crossbrowser-tests.sh
- config/custom-environment-variables.yaml
- config/default.yaml
- test/crossbrowser/supportedBrowsers.js
- test/end-to-end/paths/basicDivorce.js
no impact on master pipeline
fix E2E on nightly pipeline for IE11
> Ignore session validation on sauce lab cross browser

- bin/run-crossbrowser-tests.sh
- config/custom-environment-variables.yaml
- config/default.yaml
- test/crossbrowser/supportedBrowsers.js
- test/end-to-end/pages/marriage/upload.js
- test/end-to-end/paths/basicDivorce.js
- test/end-to-end/saucelabs.conf.js
no impact on main pipeline
fix failed tests on Edge and Safari
> fix failed tests on Edge and Safari in Saucelabs

- app/services/payment.js
Reverts hmcts/div-petitioner-frontend#521
Disabling strategic pay due to a mass amount of errors being triggered.
> Revert "Enable strategic payment solution"

- app/services/payment.js
- app/services/payment.test.js
Getting proper confirmation from Pay Team the exponential payment retries fix is live.
---
Confirmed updated payment code is in Production now, and current Production queue for payments is empty.
> Enable serviceCallbackUrl again

- app/steps/check-your-answers/index.js
- app/steps/check-your-answers/index.test.js
https://tools.hmcts.net/jira/browse/DIV-4800
PFE-CYA page - Statement of Truth check box is always checked for particular scenario which is wrong
> Statement of truth field should never be checked

- Jenkinsfile_CNP
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
TIDAM is deprecated. Pointing all envs to SIDAM
> Point to SIDAM

- Dockerfile
- Gruntfile.js
- Makefile
- README.md
- app/core/utils/baseUrl.js
- app/core/utils/baseUrl.test.js
- app/middleware/draftPetitionStoreMiddleware.js
- app/middleware/draftPetitionStoreMiddleware.test.js
- charts/div-pfe/values.yaml
- config/default.yaml
- docker/dev-compose.yaml
- docker/jenkins-compose.yaml
- package.json
- sonar-project.properties
- test/end-to-end/helpers/SessionHelper.js
- Renamed `start-dev` to `dev` to match DN and RFE
- Changed port to 3000 to match DN and RFE 
- Run the interceptor as part of Save and Close to return any calulcated values there into the session
Fixes #DIV-3532
> DIV-3532 fix missing divorce options

- app/steps/pay/pay-online-only/index.js
- app/steps/pay/pay-online-only/index.test.js
https://tools.hmcts.net/jira/browse/DIV-4743
In PFE saving /pay/online page and then relogin  will not retain feeToBePaid in session.
> Update feeToBePaid if it is not available in session

- app/services/healthcheck.js
Introduce consistency in the naming of health checks
Fixes # [DIV-3999](https://tools.hmcts.net/jira/browse/DIV-3999)
> DIV-3999: Consolidate naming of responses in health check

- app/steps/respondent/correspondence/send-to-solicitor/content.json
- app/steps/respondent/correspondence/send-to-solicitor/index.js
- app/steps/respondent/correspondence/send-to-solicitor/index.test.js
- app/steps/respondent/correspondence/send-to-solicitor/partials/checkYourAnswersTemplate.html
- app/steps/respondent/correspondence/send-to-solicitor/schema.json
- app/steps/respondent/correspondence/send-to-solicitor/template.html
- app/steps/respondent/correspondence/use-home-address/index.js
- app/steps/respondent/correspondence/use-home-address/index.test.js
- app/steps/respondent/solicitor/details/index.js
- test/fixtures/mockSession.json
https://tools.hmcts.net/jira/browse/DIV-4966
PFE - when respondent solicitor is named, set respondentSolicitorRepresented
> Mapping respondentCorrespondenceSendToSolicitor to respondentSolicitorRepresented

- app.js
- config/custom-environment-variables.yaml
Clean up. This var is not in use anymore.
https://tools.hmcts.net/jira/browse/DIV-2637
> DIV-2637: clean up - remove porttactical var

- yarn.lock
> lodash update to 4.17.14

- test/end-to-end/paths/invalidCsrf.js
- test/end-to-end/paths/payment.js
- test/end-to-end/paths/uploadMarriageCertificate.js
[DIV-2596](https://tools.hmcts.net/jira/browse/DIV-2596)
Generator Functions are no longer supported by CodeceptJS latest versions. Have changed them to use async/await in stead.
* Hardware:
* JDK:
> Change generator functions in Codecept to Async Await

- test/end-to-end/helpers/idamHelper.js
to reduce errors on notification service
> changeEmailNotificationDomain

- app.js
- app/steps/grounds-for-divorce/adultery/details/index.test.js
- app/steps/grounds-for-divorce/lived-apart-since/index.test.js
- app/steps/jurisdiction/residual/index.test.js
- app/steps/marriage/in-the-uk/index.test.js
- package.json
- test/util/assertions.js
- yarn.lock
[DIV-5354](https://tools.hmcts.net/jira/browse/DIV-5354)
This resolves some error messages appearing on Unit Tests, and fixed an issue with a failing test that was passing.
Also uses HPKP module instead of the deprecated Helmet.HPKP function.
> Adjustments to Code to resolve unit test errors

- Jenkinsfile_CNP
- package.json
[DIV-5634 - Update vault definitions for DN, RFE and PFE](https://tools.hmcts.net/jira/browse/DIV-5634)
> DIV-5634 - Update vault definitions for DN, RFE and PFE

- package.json
- test/validation/htmlTest.js
- yarn.lock
our requests to validate html keep failing so this PR adds a temporary solution to retry the request up to three times if it fails
> retry request to validate html

- app/content/common.json
[DIV-4611 - Accessibility [AA] - 'Feedback' link](https://tools.hmcts.net/jira/browse/DIV-4611)
- Update feedback aira label to have more accurate content
> update feedback content to be acurate

- app/components/AddressLookupStep/index.test.js
- app/components/AddressLookupStep/template.html
[DIV-4614 - Accessibility [A] - Focus - find address button](https://tools.hmcts.net/jira/browse/DIV-4614)
> DIV-4614 - Focus - find address button

- charts/div-pfe/Chart.yaml
- charts/div-pfe/requirements.yaml
- charts/div-pfe/values.preview.template.yaml
> Updated Dockerfile/helm to use hmctspublic

- app/steps/check-your-answers/template.html
To resolve an issue with leaked comment on HTML
> Remove NOSONAR on HTML

- infrastructure/prod.tfvars
Verified should be working fine by Krishna on Payments team.
> Enable strategic pay on Production env

- infrastructure/main.tf
Use cnp .tf dependencies rather than deprecated moj ones.
DIV-5750
- [y] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* JDK:
> Use hmcts/cnp modules

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DIV-5608
Simply updated URLS to new Smart Survey URLS
> DIV-5608: Updated Smart survey links to new urls

- app/assets/sass/application.scss
- app/steps/done-and-submitted/content.json
- app/steps/done-and-submitted/index.test.js
- app/steps/done-and-submitted/template.html
- package.json
- sonar-project.properties
[DIV-5820 - Right-hand column to show on PFE done page](https://tools.hmcts.net/jira/browse/DIV-5820)
- Added a side panel to the PFE done page
> DIV-5820 - Right-hand column to show on PFE done page

- app/components/AddressLookupStep/index.js
- app/components/AddressLookupStep/index.test.js
- package.json
- sonar-project.properties
Adds extra tests to ensure code cov for newer code.
> Fix code cov for AddressLookupStep

- app/steps/done-and-submitted/content.json
- app/steps/done-and-submitted/index.test.js
- app/steps/done-and-submitted/template.html
[DIV-5223 - Response Submitted (after amendment) page](https://tools.hmcts.net/jira/browse/DIV-5223)
- Added new content for DN reject and amend done page
> DIV-5223 - Response Submitted (after amendment) page

- charts/div-pfe/values.yaml
We had invalid name of image. This should be pfe.
> Update values.yaml: use proper image (PFE not RFE)

- package.json
> Enable only one set of failing tests

- charts/div-pfe/Chart.yaml
> bump up Chart version

- package.json
- yarn.lock
Bumping up version of yarn, as suggested by alert on GitHub.
> Bumping up version of yarn, as suggested by alert on GitHub.

- infrastructure/variables.tf
> client_id variable removed

- infrastructure/main.tf
> WLA-93: Get LD key from vault

- Jenkinsfile_CNP
> WLA-93: add LD to jenkinsfile

- app/core/components/launch-darkly.js
> Log LD Key

- app/components/AddressLookupStep/addressTypes/postcode.js
- app/components/AddressLookupStep/index.js
- app/components/AddressLookupStep/template.html
- app/steps/check-your-answers/index.js
- app/steps/done-and-submitted/template.html
- app/views/layout.html
- test/end-to-end/codecept.conf.js
- test/end-to-end/data/basicDivorceSessionData.js
Hide language toggle from Done and Submitted page.
Add language toggle on Address pages and on CYA page.
Re-enable e2e.
> WLA-93: Hide language toggle from Done and Submitted page

- test/end-to-end/paths/errorPaths.js
> WLA-93: Comment out failing e2e lines

- test/end-to-end/paths/errorPaths.js
> WLA-93: Re-enable cookie error e2e

- app/steps/grounds-for-divorce/adultery/second-hand-information/content.json
- app/steps/grounds-for-divorce/lived-apart-since/content.json
- app/steps/help/need-help/content.json
- app/steps/jurisdiction/last-habitual-residence/content.json
- app/steps/jurisdiction/residual/content.json
- app/steps/marriage/about-your-marriage-certificate/content.json
- app/steps/marriage/in-the-uk/content.json
- app/steps/prayer/claim-costs/content.json
- app/steps/respondent/correspondence/use-home-address/content.json
- app/steps/save-resume/confirm-remove-saved-application/content.json
- app/steps/screening-questions/has-marriage-broken/content.json
- app/steps/screening-questions/has-marriage-cert/content.json
- app/steps/screening-questions/has-respondent-address/content.json
https://tools.hmcts.net/jira/browse/WLA-566
> WLA-566: Amend Welsh Yes/No answers

- app/steps/screening-questions/language-preference/content.json
- app/steps/screening-questions/language-preference/template.html
https://tools.hmcts.net/jira/browse/WLA-559
> WLA-559: Amend copy on Language question

- app/steps/grounds-for-divorce/reason/content.json
https://tools.hmcts.net/jira/browse/WLA-564
> WLA-564: Add adultery explanation in Welsh

- charts/div-pfe/Chart.yaml
- charts/div-pfe/values.yaml
https://tools.hmcts.net/jira/browse/WLA-591
> WLA-591: Terraform for Welsh copy changes

- app/middleware/draftPetitionStoreMiddleware.js
https://tools.hmcts.net/jira/browse/RPET-295
> RPET-295-Amend-stuck-on-HWF

- app/steps/done-and-submitted/content.json
> Add link back

- charts/div-pfe/Chart.yaml
- charts/div-pfe/values.preview.template.yaml
- charts/div-pfe/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-390
Chart changes for PR #723
> PCQ-390: Chart changes for PCQ

- app/resources/sessionBlacklistedAttributes.json
- app/steps/amendment-explanatory-page/index.js
- app/steps/grounds-for-divorce/reason/index.js
- app/steps/grounds-for-divorce/reason/index.test.js
https://tools.hmcts.net/jira/browse/DIV-6478
> DIV-6478: When petitioner amends they should be able to select their previous reason

- app/steps/screening-questions/language-preference/content.json
- app/steps/screening-questions/language-preference/template.html
- app/views/common/components/formElements.html
https://tools.hmcts.net/jira/browse/RPET-359
* Hardware:
* JDK:
> RPET-359-Welsh-language-question-change

- package.json
I've a changed package.json to display Accessibility report.
* Hardware:
* JDK:
> Fixed Pa11y Test

- test/end-to-end/codecept.conf.js
- test/end-to-end/paths/errorPaths.js
Redirect to Login page on AAT test fix
https://tools.hmcts.net/jira/browse/TA-145
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
> TA-145-redirect to login page test fix

- test/end-to-end/pages/prayer/claim-costs.js
- test/end-to-end/paths/adulteryAndDesertionJourneys.js
- test/end-to-end/paths/exitScenarios.js
Added missing paths to Adultery and Desertion for E2E english journey.
Also added already existing exit paths for 5 years separation.
Tested locally and on AAT.
> Added Adultery, Desertion and exit scenarios

- test/end-to-end/pages/petitioner/confidential.js
- test/end-to-end/pages/prayer/claim-costs.js
- test/end-to-end/paths/adulteryAndDesertionJourneys.js
Added 'Keep my address private' functionality and also modified files to adhere to the normal coding standards.
Fixes # No Fixes
Locally and on AAT
> Adding Keep my address private functionality

- Jenkinsfile_CNP
- app/core/setup/setupSecrets.js
- app/core/setup/setupSecrets.test.js
- app/middleware/draftPetitionStoreMiddleware.js
- charts/div-pfe/values.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- config/example-local-aat.yml
- infrastructure/main.tf
- test/end-to-end/pages/index/index.js
- test/end-to-end/smoke.conf.js
- test/end-to-end/smoke/smoketest.js
> Rpet 586 smoke test update

- app/core/setup/setupSecrets.test.js
- test/end-to-end/codecept.conf.js
- test/end-to-end/pages/index/index.js
- test/end-to-end/paths/jurisdictionConnections.js
- test/end-to-end/paths/reasonsForDivorce.js
- test/end-to-end/smoke.conf.js
- test/end-to-end/smoke/smoketest.js
> RPET-586 Smoke test

- app/middleware/redirectMiddleware.js
> Improve Logging around redirect to DN

- test/accessibility/a11yTest.js
Added welsh check to the existing English test 
on Localhost and AAT
* Hardware:
* JDK:
> Added welsh accessibility check for Petitioner Frontend

- test/crossbrowser/supportedBrowsers.js
- test/end-to-end/helpers/ElementExist.js
- test/end-to-end/helpers/JSWait.js
- test/end-to-end/helpers/SauceLabsBrowserHelper.js
- test/end-to-end/helpers/idamHelper.js
- test/end-to-end/pages/help/with-fees.js
This PR includes the following crossbrowser test changes:
- run tests on `macOS 10.14` instead of latest because there's an issue with selenium scrolling elements into view where they can then no longer be interacted with by Webdriver. An update to latest Safari can be done when the issue between Saucelabs / Webdriver / Safari is resolved.
- improves a waiting in a couple of areas
- removes some broken code to do with trying to support Safari (and IE) delays
- rename of idam retry functionality to be clearer as to what's going on
- fixed wrong content being referenced in test/end-to-end/pages/help/with-fees.js
Fixes # https://tools.hmcts.net/jira/browse/TA-76
This has been tested locally with both functional and crossbrowser tests, and checked …
> Nightly Crossbrowser improvements

- test/end-to-end/paths/errorPaths.js
It was tested manually. It's some flakiness with the way the tests have been written.
> DIV-6677/DIV-6673: Skipping test to get a green build and satisfy the QA readiness report

- test/end-to-end/paths/errorPaths.js
Just skipping (rather than commenting out) the test.
> Really skipping test

- app/middleware/redirectMiddleware.test.js
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/DIV-6654
Redirecting PFE to DN when case is in `AwaitingGeneralReferralPayment` or `GeneralConsiderationComplete` state. DN already has facility to display a default informatory page for cases it does not specifically handle, no need to create on PFE
> DIV-6654: Map general referral states on Petitioner and Respondent apps

- app/steps/grounds-for-divorce/reason/index.js
As the title suggests, I'd like to add some logic to help troubleshoot the amend petition journey for a petitioner.
Awaiting the go ahead from RM so will not be merging without their say-so.
Part of ticket https://tools.hmcts.net/jira/browse/RPET-187 and https://tools.hmcts.net/jira/browse/DIV-6744 
Additional logging.
N/A
> adding some logging to help troubleshoot a case

- app/steps/respondent/correspondence/send-to-solicitor/content.json
- app/steps/respondent/correspondence/send-to-solicitor/index.js
- app/steps/respondent/correspondence/send-to-solicitor/index.test.js
- app/steps/respondent/correspondence/send-to-solicitor/template.html
- app/steps/respondent/correspondence/use-home-address/content.json
- app/steps/respondent/correspondence/use-home-address/index.js
- app/steps/respondent/correspondence/use-home-address/index.test.js
- app/steps/respondent/correspondence/use-home-address/template.html
- test/end-to-end/pages/respondent/send-to-solicitor.js
- test/end-to-end/pages/respondent/use-home-address.js
Some refactoring for DIV-6760, such as putting up to date the changes from DIV-6816.
Fixes https://tools.hmcts.net/jira/browse/DIV-6760
Unit tests
> Refactoring for DIV-6760

- package.json
- test/end-to-end/helpers/idamHelper.js
- yarn.lock
According to the IDAM team, this should make creating users a lot quicker.
Existing tests.
> DIV-6836: Using new div-idam-test-harness

- app/assets/sass/_organisation-search.scss
- app/assets/sass/application.scss
- app/views/common/components/respondentSolicitorComponents.html
https://tools.hmcts.net/jira/browse/DIV-6831
Adds a vertical scrollbar to 'search solictor organisation' results. 
https://user-images.githubusercontent.com/4429628/110936380-b72c5b00-8328-11eb-8a91-d0fa29888b0d.mov
> DIV-6831: Added scrollbars to 'search solicitor organisation' results

- app/middleware/redirectMiddleware.test.js
- config/default.yaml
> Div 5457 add valid states

- app/steps/respondent/correspondence/solicitor-search/content.json
https://tools.hmcts.net/jira/browse/DIV-6850?focusedCommentId=992268&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-992268
```
jeremy.katz Jeremy Katz added a comment - 22 minutes ago
Here's the translation for "If you can't see the firm listed then you can enter the details manually.”
Welsh: "Os na allwch weld y cwmni wedi'i restru yna gallwch nodi’r manylion eich hun."
```
> DIV-6850-Add Welsh translation for searchNoOptionFoundText

- app/steps/respondent/correspondence/send-to-solicitor/content.json
Adds in a missing question mark
Fixes # https://tools.hmcts.net/jira/browse/DIV-6850
> DIV-6850 - Add missing question mark

- app/steps/service-application-not-approved/content.json
- app/steps/service-application-not-approved/index.js
- app/steps/service-application-not-approved/index.test.js
Landing page has been modified to display values appropriately.
Fixes https://tools.hmcts.net/jira/browse/DIV-6880
Unit tests
> DIV-6880: Adding logic for bailiff scenario. Service application not approved landing page

- Jenkinsfile_nightly
- package.json
> DIV-6907: Increasing time-out for cross-browser tests and adding functional tests to nightly pipeline

- Jenkinsfile_nightly
- bin/run-crossbrowser-tests.sh
- yarn.lock
This is hopefully going to make this step quicker.
> DIV-6907: Making cross browser tests run in parallel

- app/steps/grounds-for-divorce/separation-date/index.test.js
they are passing locally, I don't understand why they were skipped.
> unskip tests

- Jenkinsfile_nightly
- test/end-to-end/paths/aboutYourMarriageCertificate.js
> DIV-6907: Logging which TEST URL is being used and archive test results

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- bin/run-crossbrowser-tests.sh
- test/end-to-end/pages/index/index.js
I believe this is making functional tests fail on nightly pipeline.
> DIV-6907: Enabling IDAM feature for nightly pipeline

- Jenkinsfile_nightly
- package.json
- test/end-to-end/pages/marriage/upload.js
- test/end-to-end/pages/screening-questions/language-preference.js
- test/end-to-end/paths/startSession.js
- test/end-to-end/paths/staticPages.js
- test/end-to-end/paths/uploadMarriageCertificate.js
- test/end-to-end/saucelabs.conf.js
- yarn.lock
> DIV-6907: Fixing at least a few tests

- app/routes/sign-out.js
- config/development_template.yaml
- package.json
- test/end-to-end/paths/logout.js
- yarn.lock
> DIV-6907: Trying to fix sign out feature tests

- test/end-to-end/helpers/SauceLabsReportingHelper.js
> DIV-6907: Improving cross-browser test reports

- test/end-to-end/pages/screening-questions/has-respondent-address.js
- test/end-to-end/paths/basicDivorce.js
- test/end-to-end/paths/logout.js
> Checking basic divorce scenario runs on Jenkins

- test/end-to-end/paths/basicDivorce.js
- test/end-to-end/paths/save-resume.js
> DIV-6907: Hardcoding divorce reason

- test/end-to-end/paths/basicDivorce.js
> DIV-6907: Hardcoding the reason for divorce

- bin/run-crossbrowser-tests-local.sh
- bin/run-crossbrowser-tests.sh
> DIV-6907: Setting XB test up with contact information.

- test/end-to-end/pages/exit/save-and-close.js
- test/end-to-end/pages/index/index.js
- test/end-to-end/paths/errorPaths.js
- test/end-to-end/paths/logout.js
- test/end-to-end/paths/save-resume.js
> DIV-6907: Fixing skipped tests

- test/end-to-end/pages/index/index.js
> DIV-6907: Finding element by id, not text.

- test/end-to-end/pages/index/index.js
- test/end-to-end/pages/marriage/date.js
- test/end-to-end/pages/petitioner/confidential.js
- test/end-to-end/paths/adulteryAndDesertion-en.js
- test/end-to-end/paths/invalidCsrf.js
> DIV-6907: Fixing nightly tests

- package.json
- yarn.lock
- Enforce Div Pay Client to use 7.0.1
> Enforce div pay client version

- app/views/cookie-error.html
https://sonarcloud.io/project/issues?id=FeatureToggleStudy_div-petitioner-frontend&open=AW5BcIGg6cM7nDSGUpp4&resolved=false&types=VULNERABILITY
> fix sonar issue

- app/services/postcodeInfo.js
- app/steps/marriage/date/content.json
- charts/div-pfe/Chart.yaml
- charts/div-pfe/values.yaml
- config/example-local-aat.yml
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DFR-118
> DFR-118 Change postcode lookup url to new service

- app.js
- app/steps/avaya-webchat/template.html
- app/views/includes/head.html
- app/views/includes/web_chat.html
- charts/div-pfe/values.preview.template.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- test/end-to-end/paths/reportAProblemPath.js
Implements new API call to Webchat client behind a feature toggle and removes old Webchat 8x8 code
[DFR-119](https://tools.hmcts.net/jira/browse/DFR-119)
- [ x] New feature (non-breaking change which adds functionality)
> Dfr 119 antenna webchat api change

- app/services/mocks/feesAndPaymentsService.js
- app/steps/pay/pay-online-only/index.js
- app/steps/pay/pay-online-only/index.test.js
- app/steps/service-application-not-approved/index.js
- app/steps/service-application-not-approved/index.test.js
- charts/div-pfe/Chart.yaml
- charts/div-pfe/values.yaml
- config/default.yaml
> DFR-435: Switch on fees

- app/middleware/submissionMiddleware.test.js
- app/services/mocks/feesAndPaymentsService.js
- app/services/mocks/payment.js
- app/services/payment.test.js
- app/services/submission.test.js
- app/steps/done-and-submitted/index.js
- app/steps/done-and-submitted/index.test.js
- app/steps/financial/arrangements/index.js
- app/steps/financial/arrangements/index.test.js
- app/steps/help/need-help/index.js
- app/steps/help/need-help/index.test.js
- app/steps/pay/pay-online-only/index.js
- app/steps/pay/pay-online-only/index.test.js
- app/steps/service-application-not-approved/index.js
- app/steps/service-application-not-approved/index.test.js
- config/default.yaml
- test/end-to-end/pages/pay/by-card-online-on-govpay.js
- test/end-to-end/pages/pay/pay-online-only.js
- test/end-to-end/paths/adulteryAndDesertion-en.js
- test/end-to-end/paths/payment.js
> DFR-437: Remove feature flag

- app/middleware/checkCookiesAllowed.js
JIRA
https://tools.hmcts.net/jira/browse/DFR-656
> DFR-656 cookie security Fortify fix

- app/assets/javascripts/cookiesManager.js
- yarn.lock
Test for presence of cookie elems before calling onClick()
> DFR-37-Webchat-Fix

- test/end-to-end/paths/errorPaths.js
> fix failing Ft test

- charts/div-pfe/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1120
> Update Node Chart.yaml

- infrastructure/main.tf
> Updating app key

- app/assets/locale/locale_en-GB.json
Update contactCenterClosed value
> DFR-1045 Update contactCenterClosed text

- charts/div-pfe/Chart.yaml
- charts/div-pfe/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1395
> Autoscaling

- Jenkinsfile_nightly
> Removing cross browser tests array

- Jenkinsfile_CNP
- README.md
- charts/div-pfe/Chart.yaml
Reconfigure the jenkins file inline with changes made to the pipeline in DTSPO-9025 (which moves label checks and additional test execution logic into the pipeline itself).
> Reconfig for dtspo 9025

- .github/CODEOWNERS
- .github/renovate.json
https://tools.hmcts.net/jira/browse/DTSPO-12024
Configure renovate to update helm chart dependencies
Add codeowners
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
> DTSPO-12024 - Configure renovate
