hmcts/div-petitioner-frontend

app/core/DestroySessionStep.js, app/core/DestroySessionStep.test.js, app/services/idam.js, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/DIV-2000
Add Login functionality to the divorce application on save&close, exit and done.
This is the frontend bit of the code. It requires the corresponding idam express middleware to be built and added to node modules for this to work..
DestroySessionStep has been updated to make a middleware call to idam to delete session token.
=> Div 2000 logout

app/components/AddressLookupStep/index.js
[DIV-2201 - Throwing Generic Error when click on SaveAndClose button](https://tools.hmcts.net/jira/browse/DIV-2201)
Bug fix for issue regarding save and close, bug details:
Dominic Taylor, when I tried to complete the journey after resuming from the steps in the bug, you end up with a broken address page (see below screenshot), and trying to continue causes a "No addresses found error"
Steps to recreate:
- resume a previously saved divorce (that was saved on the /petitioner-respondent/address page with 
- empty address details as per the original bug)
- enter postcode and click 'find address'
- ISSUE 1: page loads with 2 'save and close' links
- select an address from the drop-down list
- ISSUE 2: page loads with an error message "No addresses found. Enter a postcode to search again" even …
=> fix save and close bug

app/core/ValidationStep.js, app/middleware/idamProtectMiddleware.js, app/middleware/idamProtectMiddleware.test.js, app/middleware/setIdamDetailsToSessionMiddleware.js, app/middleware/setIdamDetailsToSessionMiddleware.test.js, app/steps/marriage/upload/index.js, app/steps/pay/card-payment-status/index.js, app/steps/pay/pay-online-only/index.js, app/steps/pay/pay-online-only/index.test.js, app/steps/submit/index.js, package.json, test/util/assertions.js, yarn.lock
[DIV-2110 - Save and Resume: email address not displayed after save if draft previously deleted](https://tools.hmcts.net/jira/browse/DIV-2110)
[DIV-1795 - SECURITY: /pay/online page is not behind IDAM](https://tools.hmcts.net/jira/browse/DIV-1795)
- Refactors idam protect to return userDetails
- Adds new middleware to handle setting idam email to session
- Ensures all pages are using correct middleware ( i.e. idam protect, session, etc ... )
=> Set email from idam user details

app/middleware/setIdamDetailsToSessionMiddleware.js, app/steps/authenticated/index.js, app/steps/authenticated/index.test.js
[DIV-2110 - Save and Resume: email address not displayed after save if draft previously deleted](https://tools.hmcts.net/jira/browse/DIV-2110)
- Corrects incorrect reference to email from idam
- Removes stale code for setting email on idam login
=> correct email reference and remove old set email code

app/steps/pay/pay-online-only/index.js, app/steps/pay/pay-online-only/index.test.js, package.json, yarn.lock
Throwing an error when Case ID is not provided.
https://tools.hmcts.net/jira/browse/DIV-1956
Promise rejects when case ID/reference is not provided
Error is logged in this scenario as well
Unit tests updated to cover this scenario
This will prevent payments with invalid case ID being forwarded to prod Gov Pay subsequently
=> Div 1956 invalid case ref hitting gov pay

app/steps/grounds-for-divorce/adultery/details/index.js, app/steps/grounds-for-divorce/adultery/details/index.test.js, app/steps/grounds-for-divorce/adultery/details/partials/checkYourAnswersTemplate.html, app/steps/grounds-for-divorce/adultery/when/index.js, app/steps/grounds-for-divorce/adultery/when/index.test.js, app/steps/grounds-for-divorce/adultery/where/index.js, app/steps/grounds-for-divorce/adultery/where/index.test.js, test/util/assertions.js
[DIV-2252](https://tools.hmcts.net/jira/browse/DIV-2252)
Previously, when the user selects No to Adultery Know When and Adultery Know Where questions, the details of these would be left empty.
It is a new requirement for there to be default text displayed on the Divorce Mini Petition when those values are set to No.
As the mini petition is a digitally signed document, the user must be made aware of the content, thus we are adding the default statement to the users Check Your Answers page when Know When and Know Where are set to 'No'.
In order to meet requirements for the mini petition to show Adultery Know When and Adultery Know Where details, without causing a legal issue.
The Adultery Know When and Know Where Details are now set to a default string when the user posts the form on the …
=> Fix flow of adultery when and where to include default statement when No

test/end-to-end/helpers/featureToggleHelper.js
This change fixes the feature toggle helper so that promises are correctly added to Codecept promise queue for e2e tests to use. Uses `_beforeSuite()` hook.
Have tested locally with @tchow8 to prove that the original situation where feature toggle results were resolving AFTER tests had already started no longer occurs. Have also run tests against DevA to see that promises still resolve properly.
* Hardware: Dell
* O/S and version: Linux
* JDK: n/a
=> Fix for e2e feature toggle request not resolving properly

app/steps/grounds-for-divorce/adultery/details/template.html
Removed `div`s that were wrapped around text areas in the `reason-for-divorce/adultery/details` page because the had the same id as the text area itself. 
Fixes # DIV-[2271 DIV- Accessibility -Duplicate ID’s- reason-for-divorce/adultery/details pages](https://tools.hmcts.net/jira/browse/DIV-2271)
Tested the new version and made sure it looks the same as the previous version of the code.
=> DIV- Accessibility -Duplicate ID’s- reason-for-divorce/adultery/details pages

test/end-to-end/codecept.conf.js
This change adds nightmarejs `proxy-server` option to codecept.conf.js for running e2e tests locally. To use locally, set `E2E_PROXY_SERVER` env var.
Fixes # ability to run e2e tests locally through a proxy.
This has been tested locally both with and without `E2E_PROXY_SERVER` being set, as well as via a Jenkins job again both with and without the env var being set.
* Hardware: Jenkins + local
=> CNP codecept proxy change

app/steps/bye/index.js, app/steps/bye/index.test.js, app/steps/done-and-submitted/index.js, app/steps/done-and-submitted/index.test.js, app/steps/exit/about-your-marriage/no-certificate-translated/index.js, app/steps/exit/screening-questions/has-marriage-broken/index.js, app/steps/exit/screening-questions/has-marriage-broken/index.test.js, app/steps/exit/screening-questions/has-marriage-cert/index.js, app/steps/exit/screening-questions/has-marriage-cert/index.test.js, app/steps/exit/screening-questions/has-respondent-address/index.js, app/steps/exit/screening-questions/has-respondent-address/index.test.js, app/steps/save-resume/removed-saved-application/index.js, app/steps/save-resume/removed-saved-application/index.test.js, app/steps/save-resume/save-and-close/index.js, app/steps/save-resume/save-and-close/index.test.js, app/steps/timeout/index.js, app/steps/timeout/index.test.js
It seems that when the session is destroyed, express does not delete the `connect.sid` cookie. That's why we delete the cookie manually in the exit pages
Fixes # [DIV-2498](https://tools.hmcts.net/jira/browse/DIV-2498)
This will be tested on Dev A on Tactical first
=> Clear the connect.sid cookie from exit pages

infrastructure/prod.tfvars
Production was pointing to tactical IDAM private beta.
=> Changed to public IDAM login url

app/steps/screening-questions/has-marriage-cert/index.test.js
[DIV-2622 - Frontend test failing intermittently](https://tools.hmcts.net/jira/browse/DIV-2622)
Removes unused call to `withSession` which is conflicting with a test causing to break it occasionally
Manually
=> remove unused withSession call

.nsprc, app.js, app/middleware/idamProtectMiddleware.js, app/middleware/idamProtectMiddleware.test.js, app/middleware/setIdamDetailsToSessionMiddleware.js, app/middleware/setIdamDetailsToSessionMiddleware.test.js, app/services/idam.js, app/services/idam.test.js, app/services/sessionSerializer.js, app/services/sessionSerializer.test.js, app/steps/authenticated/index.js, app/steps/pay/card-payment-status/index.js, app/steps/pay/card-payment-status/index.test.js, app/steps/pay/pay-online-only/index.js, app/steps/pay/pay-online-only/index.test.js, package.json, yarn.lock
[DIV-2454 - Change how we parse and extract data from the tactical iDAM JWT token - front-end](https://tools.hmcts.net/jira/browse/DIV-2454)
To enable us to remove JWT token parsing on the frontend we need to be able to get idam details earlier in the middleware stack without redirecting use if call fails. This PR adds new functionality that:
1. Uses the updated `div-idam-express-middleware`
2. Gets idam user details earlier in middleware stack and sets to req.idam
3. changes all references to idam JWT token to use `req.idam.userDetails`
Manually, unit/e2e tests
=> Remove use of IDAM JWT token to get user id

app/middleware/evidenceManagmentMiddleware.js, app/steps/grounds-for-divorce/desertion/details/content.json, app/steps/grounds-for-divorce/desertion/details/schema.json
[DIV-2259 - Desertion details page rendering Too large Payload when i submit Desertion Summary Text size has 20k characters](https://tools.hmcts.net/jira/browse/DIV-2259)
This PR fix this bug. If the desertion details is more than 20000 chars and error message is returned.
Manually, units
=> Div-2259 add desertion max size

app/steps/authenticated/index.js, app/steps/authenticated/index.test.js, test/util/assertions.js, test/util/setup.js
[DIV-2014 - 1 day spike: After session timeout user needs to sign in twice](https://tools.hmcts.net/jira/browse/DIV-2014)
After a user has logged into IDAM reset the session expiry date
Manually and unit test
=> reset session expiry after idam login

Jenkinsfile_CNP, config/custom-environment-variables.yaml, test/end-to-end/codecept.conf.js, test/end-to-end/paths/aboutYourMarriageCertificate.js, test/end-to-end/paths/basicDivorce.js, test/end-to-end/paths/cookieBanner.js, test/end-to-end/paths/errorPaths.js, test/end-to-end/paths/foreignMarriageCertificates.js, test/end-to-end/paths/invalidCsrf.js, test/end-to-end/paths/jurisdictionConnections.js, test/end-to-end/paths/livingTogether.js, test/end-to-end/paths/logout.js, test/end-to-end/paths/payment.js, test/end-to-end/paths/postcode.js, test/end-to-end/paths/reasonsForDivorce.js, test/end-to-end/paths/reportAProblemPath.js, test/end-to-end/paths/save-resume.js, test/end-to-end/paths/startSession.js, test/end-to-end/paths/staticPages.js, test/end-to-end/paths/uploadMarriageCertificate.js
This change includes 3 attempts to reduce load on Jenkins build agents and improve stability by:
1. E2E tests have been reduced to basicDivorce only on PR build pipeline in Preview temporarily, while test stability in Preview env is improved. #DIV-2810 has been raised to revert this behaviour once these tests are stable.
2. Codecept will no longer restart the chromium browser for every e2e test, in a bid to reduce the amount of load on Jenkins and improve test run time. However, it will still clear out cookies and browser cache, so should keep the tests clean.
3. Parallelisation has been reduced from 5 "chunks" (a.k.a. shards) to 2 on Preview env, to reduce the number of Chromium browsers open at any one time.
4. Allows each test to retry up to 3 times to work around environment issues. …
=> Reduce build agent load and speed up e2e tests

app.js, app/services/healthcheck.js, config/custom-environment-variables.yaml, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars, infrastructure/variables.tf
Temporary quick fix so that we don't get issues when tactical env goes does again.
Removes feature-toggle-api healthcheck (since we ave commented out using that url) and also changes redis url from tactical to cnp.
=> Comment out url for feature-toggle-api and use configs

app/assets/sass/_check-your-answers.scss
[DIV-1448 - Text not wrapping correctly on CYA](https://tools.hmcts.net/jira/browse/DIV-1448)
Remove css rules that are breaking the words on CYA page
Manually
=> Cya textwrap

app/core/steps/DestroySessionStep.js, app/core/steps/DestroySessionStep.test.js, app/core/steps/Step.js, app/core/steps/Step.test.js
[DIV-2498 - Error decrypting Redis when logging on](https://tools.hmcts.net/jira/browse/DIV-2498)
A fix to ensure after login out of the system you are able to login with a different user.
Yes manually
=> remove stale cookies on logout

test/end-to-end/paths/save-resume.js
This change improves the thoroughness of the `save-resume.js` e2e test, because without verifying that the journey starts from the beginning again after deleting a draft, the test is working on assumptions that might not be true.
Fixes # the test, innit
This has been tested locally against AAT.
* Hardware: mac
* O/S and version: OSX
* JDK:
=> E2E test improvement for save & resume

bin/run-functional-tests-local.sh, bin/run-functional-tests.sh, package.json, test/end-to-end/codecept.conf.js, test/end-to-end/helpers/idamHelper.js, yarn.lock
Updated idamExpressTestHarness to latest 1.1.0, and related change in idamHelper.js
Updated idamExpressTestHarness to latest 1.1.0, and made a necessary change in idamHelper.js to pass the `E2E_PROXY_SERVER` value through for benefit of running locally against Preview. 
This has been tested locally pointing to a preview instance to verify that IDAM test user can still be generated.
* Hardware: Mac
* O/S and version: OSX
* JDK:
=> Update to latest idamExpressTestHarness for benefit of running tests locally against Preview

app/steps/petitioner/confidential/content.json, app/steps/petitioner/confidential/template.html
Content change to stop users who live with their spouse from asking to keep their contact details private.
=> Urgent content change to confidential details screen

app/steps/check-your-answers/index.js, app/steps/check-your-answers/index.test.js
Check that all the addresses having an uk address selected has also a populated addressBaseUK field. Populate this field if it's missing.
This could happen only with some old draft stored before 26 of june 2018
- [ x] New feature (non-breaking change which adds functionality)
- Use the PR 232 to create a submission without addressBaseUk field. The PR 232 will not create the addressBaseUK field the first time an address is selected for the post code E2 0DP.
- After have selected an address, Save and close. Login again and use Swagger to check the session has no addressBaseUK field for the address in E2 0DP
- Log in PR 231 this time and add all missing fields, just before submission check the address field addressBaseUk is still missing. Click on …
=> Add missing addressBaseUK fields

app/steps/check-your-answers/index.js, app/steps/check-your-answers/index.test.js
[DIV-2979](https://tools.hmcts.net/jira/browse/DIV-2979)
D8StatementOfTruth which is mapped from DivorceSession.confirmPrayer was not being set in CCD. The reason was a change which no longer did submission after the CYA but as part of it, meaning the confirmPrayer variable was never added to the session before submission to CCD, but only after it, meaning it wasn't saved.
This would mean D8StatementOfTruth is null in CCD for these scenarios.
The second scenario where D8StatementOfTruth is set to 'No' would occur if the user did a Save and Close on CYA and then resumed and submitted.
The change basically adds in adding the current ctx to the session before the submission occurs.
=> Fix bug where confirmPrayer was not being added to the session

test/end-to-end/pages/address/manual.js
This is a fix for the manual postcode e2e tests, where puppeteer `click()` was not waiting sufficiently before trying to fill the field. Now it uses `nacByClick()` to correctly wait for all Network traffic to finish before trying to continue.
Fixes # master
This has been tested locally against AAT and proves the fix works, and will run on Preview.
* Hardware:
* JDK:
=> stability fix for manual postcode e2e test

test/end-to-end/codecept.conf.js, test/end-to-end/pages/pay/by-card-online-on-govpay.js
Our existing seeCurrentUrlEquals which is a codecept method is being intercepted in the JSWait Helper class and waits for the DOM Element #content before proceeding.
Gov.UK Payment page recently changed the id of that element to #maincontent instead meaning our E2E tests no longer  find what we are expecting and the test times out and fails.
This PR changes the seeCurrentUrlEquals to a WaitInUrl (also codecept function) that does a similar thing to seeCurrentUrlEquals but with improved checking for page load logic, but more importantly does not check for a DOM element that isn't in our control.
=> [PREVIEW] Use waitInUrl instead of seeCurrentUrlEquals

app/core/utils/parseBool.js, app/core/utils/parseBool.test.js, app/middleware/submissionMiddleware.js, test/end-to-end/paths/errorPaths.js
When infrastructure variables are taken in by config, they are converted to String. Locally this is the case as well when trying to pass in an env variable such as FEATURE_REDIRECT_TO_APPLICATION_SUBMITTED=false, the code treats that as boolean true strangely. Passing is as false directly to the default.yml does not have this issue.
This code change parses the passed in parameter and if string, checks its equivalent to a string 'true' or if not, to the Boolean true.
=> Parse the boolean for the flag so even strings resolve correctly

infrastructure/variables.tf
I believe the problem being. We take these values as true: true, "true", 1
We were passing to Azure true. It was converting it 1. But then teh configs convert it to "1"
=> Fix for prod not using feature flag

test/end-to-end/codecept.conf.js, test/end-to-end/pages/pay/by-card-online-on-govpay.js
Reusing 5 threads since it wasn't a concurrency issue.
The test was failing because the Button Text on Gov Pay site was changed from 'Go Back and Try The Payment Again' to 'Continue'.
For now I've done the quick change. We can discuss how to handle third party service content later.
=> Fix failing e2e test

app/services/healthcheck.js
Passing in options as an object in the options object doesn't work, it must be part of the healthcheck options object itself. This should mean the timeouts take effect from config now, so 2s instead of 5s.
This should fix our false positive healthcheck timeouts as cos can take up to 3s to return, lower than the 2s max.
Our config already had 5s as the timeout, but it wasn't being used correctly as it was passed into the node healthcheck incorrectly. This PR fixes that. Currently testing in sprod.
=> Fix healthchecks

app/steps/grounds-for-divorce/adultery/details/content.json, app/steps/grounds-for-divorce/adultery/details/template.html
[DIV-3669 - Add content warning users not to leave SOC blank in adultery cases](https://tools.hmcts.net/jira/browse/DIV-3669)
RDCs have asked to add a line that warns people about not submitting enough information in their adultery SOC.
=> [PREVIEW] - Update content on adultery SOC

app/middleware/idamProtectMiddleware.test.js, app/middleware/setIdamDetailsToSessionMiddleware.test.js, app/services/transformationServiceClient.test.js, app/steps/pay/card-payment-status/index.test.js, app/steps/pay/pay-online-only/index.test.js, app/steps/petitioner/contact-details/index.test.js, test/end-to-end/helpers/idamHelper.js
https://tools.hmcts.net/jira/browse/DIV-3830
Replace ‘email@email.com’ from emails from integration tests as it is spamming notification service when we run integration tests. 
Created new HMCTS Divorce gmail account for testing with unique users
=> DIV-3830: Changed simulate email address with valid gmail for int tests

infrastructure/main.tf
From devops:
There's a bug in the azurerm provider, pin your azurerm provider to version 1.19.0 to fix
=> Fix azurerm provider number to 1.19.0

infrastructure/prod.tfvars
in line with AAT
The current settings are:
variable "court_eastmidlands_weight" {
default = 0
}
variable "court_westmidlands_weight" {
default = 0
}
variable "court_southwest_weight" {
default = 0.5
}
variable "court_northwest_weight" {
default = 0.5
}
variable "court_service_centre_weight" {
default = 0.30
}
variable "court_service_centre_divorce_facts_ratio" {
type = "map"
default = {
"unreasonable-behaviour" = 1
"separation-2-years" = 0
"separation-5-years" = 0
"adultery" = 0
"desertion" = 0
}
}
variable "divorce_facts_ratio" {
type = "map"
default = {
"unreasonable-behaviour" = 0.30
"separation-2-years"     = 0.37
"separation-5-years"     = 0.21
"adultery"               = 0.11
"desertion"              = 0.01
}
}
I think the facts ratio takes priority, so setting 1 on CTSC gives all …
=> Brings the prod config court allocation ratios

app/steps/screening-questions/has-marriage-cert/index.test.js, app/steps/screening-questions/has-marriage-cert/template.html, app/steps/screening-questions/has-respondent-address/index.test.js, app/steps/screening-questions/has-respondent-address/template.html
Re-apply the saveAndClose block, as an empty block, so no Save And Close button gets rendered out. This draft store functionality is not intended for screening questions.
Fixes # DIV-4005
Manual testing
=> DIV-4005 apply empty saveAndClose block to ensure no button show

infrastructure/output.tf
For E2E tests to pickup.
default.yml has the feature_release_510 flag as true, but the envs are set to false. This means the tests are picking up the default config. This adds to the output.tf the current env value so that is correctly passed to the test config.
=> Add missing feature_release 510 to the env outputs

app/core/steps/ValidationStep.js, app/core/steps/ValidationStep.test.js, app/middleware/draftPetitionStoreMiddleware.js, app/steps/save-resume/confirm-remove-saved-application/index.js, sonar-project.properties, test/end-to-end/data/amendPetitionSession.js, test/end-to-end/helpers/SessionHelper.js, test/end-to-end/pages/index/index.js, test/end-to-end/paths/save-resume.js
Fixes a bug where user returns to confirm delete page after already confirming they wish to delete.
[Amend Petition: CYA- Even after deleting application - the draft still exists](https://tools.hmcts.net/jira/browse/DIV-4288)	
Manual, unit, functional
=> DIV-4288 Allow for delete application path navigation when Amend Petition

app/services/payment.js
To possibly resolve the heavy cpu usage issue in prod, until an actual solution is put into place.
=> Temporarily disable payment callback url being used

package.json, yarn.lock
Forced update versions of Braces to remove vulnerabilities
Before:
3 vulnerabilities found - Packages audited: 17920
Severity: 3 Low
After:
1 vulnerabilities found - Packages audited: 18266
Severity: 1 Low
=> DIV-4362: Forced dependency version of braces to remove 2 vulnerabilities

test/end-to-end/saucelabs.conf.js
it helps to run nightly tests quicker
https://wiki.saucelabs.com/display/DOCS/Sauce+Labs+European+Data+Center+Configuration+Information
=> Add region specific to run nightly tests on European data centre

Gruntfile.js, package.json, test/end-to-end/saucelabs.conf.js, yarn.lock
Locally starting and server and setting up assets was failing due to grunt-sync.
There is a deprecation notice for grunt-sync at https://www.npmjs.com/package/grunt-sync, with the note that it is similar to https://github.com/gruntjs/grunt-contrib-copy.
So this PR migrates the grunt-sync code over to grunt-contrib-copy instead.
=> Migrated grunt-sync to grunt-contrib-copy

Gruntfile.js, app/core/helpers/steps.js, app/core/helpers/steps.test.js, app/core/steps/Step.js, app/core/steps/Step.test.js, app/steps/check-your-answers/index.js, app/steps/check-your-answers/index.test.js, package.json, test/end-to-end/codecept.conf.js, test/end-to-end/data/amendPetitionSessionWithConfirmation.js, test/end-to-end/helpers/SessionHelper.js, test/end-to-end/pages/index/index.js, test/end-to-end/paths/amend.js, test/end-to-end/paths/payment.js, test/end-to-end/paths/save-resume.js
This is to fix a scenario where skipping answered questions still stops
at Check Your Answers, because the user could have answered a question,
then clicked saved an resume, which means they come back, the page is
skipped and the case is not submitted
Fixes #DIV-4583
=> DIV-4583 - fix incorrect step skipping on amend petition

app/steps/authenticated/index.js, app/steps/authenticated/index.test.js
[DIV-4366 - Amend petition : When we move from DN to PFE - internal server error- intermittent](https://tools.hmcts.net/jira/browse/DIV-4366)
- Fix bug where 500 error being returned to the user due to session being destroyed without being regenerated
=> fix error where session is being destroyed

app/steps/save-resume/confirm-remove-saved-application/index.js, app/steps/save-resume/confirm-remove-saved-application/index.test.js
Sometimes the draft was not getting deleted after going to the delete draft page.
Actually, the draft was getting deleted, but there was a race condition with the saveDraft postMiddleware on the confirm delete draft page. Most of the time, the saveDraft middleware resolves first, but rarely the deleteDraft middleware will resolve first and the saveDraft one happens immediately after.
This fix removes the postMiddleware from being called by the confirm delete page, as there is no reason to save the answer to 'Do you want to delete your draft'.
Maybe a discussion to see if we can enforce request orders may be required, i.e. resolve all promises before triggering the res.redirect on a POST request.
https://tools.hmcts.net/jira/browse/DIV-4509
Please delete options that are …
=> Remove default postMiddleware in delete draft scenario

.gitignore, package.json, yarn.lock
Was using a very old version of sonar-scan. Updating to the latest 3.1.0 which both RFE and DN use.
=> Update sonar-scanner module version

app/steps/marriage/date/index.test.js
Basically, today's date is 29/04/2019
The failing test does:
Years - 100
Month - 1
Day - Same
However, on today's date, this results in the following date:
29/02/1919 (because month is 0 indexed, i.e. January is 00, so April is 03, so -1 results in 2, which when used in the citizen UI context relates to February)
Being a non-leap year day, 29 is not a valid date, resulting in the Invalid Date error showing instead of 100 years in the past.
This PR tries to resolve for that scenario by forcing the day component to be 1.
=> Use hardcoded day value so differing month days don't throw an error

app/steps/living-arrangements/last-lived-together/at-petitioner-home-address/partials/checkYourAnswersTemplate.html, app/steps/petitioner/correspondence/use-home-address/partials/checkYourAnswersTemplate.html, app/steps/respondent/correspondence/use-home-address/partials/checkYourAnswersTemplate.html, app/steps/respondent/home/lives-at-last-address/partials/checkYourAnswersTemplate.html
[DIV-4738](https://tools.hmcts.net/jira/browse/DIV-4738)
This PR moves the display of addresses on the Check Your Answers page to the centre column.
* Hardware:
* JDK:
=> Change layout for Addresses on CYA

app/middleware/draftPetitionStoreMiddleware.test.js
A new test was introduced as part of #541, which was somehow causing a memory leak in tests
```
[Unit tests and Sonar scan] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[Unit tests and Sonar scan]  1: node::Abort() [/usr/bin/node]
[Unit tests and Sonar scan]  2: 0x8ccf9c [/usr/bin/node]
[Unit tests and Sonar scan]  3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
[Unit tests and Sonar scan]  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
```
Fixes #DIV-4860
=> DIV-4860 - removed unnecessary sandbox stubbing

charts/div-pfe/values.yaml, infrastructure/variables.tf, test/end-to-end/data/amendPetitionSession.js
[DIV-5103 - Update email address for divorce cases](https://tools.hmcts.net/jira/browse/DIV-5103)
- change contactdivorce@justice.gov.uk to divorcecase@justice.gov.uk
=> DIV-5103 - Update email address for divorce cases

Dockerfile
> Next monday we will be changing the registry the pipeline will be pushing to by default
> the registry will be changing from:
> hmcts => hmctspublic
> you will no longer need to log in to pull your images (because it is a public registry, same as dockerhub)
> the name of the "repo" will change from
> "hmcts/product-component" => "product/component"
=> Update to use the public HMCTS docker registry

app/assets/sass/application.scss
[DIV-883 Cross-Browser - Mobile - No Padding on postcode lookup](https://tools.hmcts.net/jira/browse/DIV-883)
- added margin to postcode field when on mobile device
=> Cross-Browser - Mobile - No Padding on postcode lookup

package.json, yarn.lock
Remove `nsp` from project. This is not used anymore and it was causing security issue
=> Removed nsp from project - deprecated package

package.json, yarn.lock
Using the latest version of div-pay-client, 7.0.0 has fixed all security issue, upgraded all packages and nodejs is upgraded to 10.15.2
=> Use div-pay-client 7.0.0

charts/div-pfe/values.preview.template.yaml, config/default.yaml, infrastructure/variables.tf
[DIV-5756 - Enable webchat on live environment](https://tools.hmcts.net/jira/browse/DIV-5756)
- Remove chart specific config
- Set webchat default to true
- Set webchat default on true for PROD and AAT environments
=> DIV-5756 - Enable webchat on live environment

test/end-to-end/paths/errorPaths.js
If we clear cookies it goes to login page, we no more going to see cookie error page on master/AAT.
Only on Preview it's redirecting to cookie-error page.
=> cookies-error test fix

config/default.yaml, package.json, test/crossbrowser/supportedBrowsers.js, test/end-to-end/helpers/ElementExist.js, test/end-to-end/helpers/JSWait.js, test/end-to-end/helpers/SauceLabsReportingHelper.js, test/end-to-end/helpers/SessionHelper.js, test/end-to-end/paths/reasonsForDivorce.js, test/end-to-end/saucelabs.conf.js
This change updates CodeceptJS, Puppeteer and Webdriver to latest or nearly latest stable versions.
As part of this, updates were made to 
- follow CodeceptJS's move to `Webdriver` helper
- fix ElementExist to wait for element
- update crossbrowser tests to run `@nightly` tagged tests instead of hardcoded to _basicDovorce.js_
- fix saucelab.conf.js's waitForTimeout reference
- update supportedBrowsers.js to test on the latest Mac and Windows OSs
Fixes # https://tools.hmcts.net/jira/browse/TA-155
This has been run locally against AAT and via Jenkins build, with both passing.
* Hardware:
* JDK:
=> Chore: e2e and crossbrowser version bumps

test/end-to-end/helpers/idamHelper.js, test/end-to-end/paths/amend.js, test/end-to-end/paths/serviceApplicationNotApproved.js
TLDR: Add retries to idamHelper.js for the e2e tests, and `.retry(2)` to @functional tagged tests that didn't already have them to better handle AAT dependency issues.
**Changes:**
1. It turns out Codecept doesn't retry `_before()` hooks, so any time an IDAM user creation failed it would fail the test. So this refactor adds 2 retries (i.e. up to 3 attempts) to create a user.
2. Tests were failign when removing IDAM test users, but this has nothing to do with Divorce functionality as it's just test cleanup. So errors experienced during IDAM test user removal will now be printed to logs but not thrown.
3. The previous logging method didn't actually print anything anywhere, making debugging very difficult. So this will now report to console logs both successful and unsuccessful attempts, …
=> Feature: Add retries to idamHelper.js and some e2e tests

bin/run-crossbrowser-tests.sh, config/custom-environment-variables.yaml, test/crossbrowser/supportedBrowsers.js, test/end-to-end/helpers/ElementExist.js, test/end-to-end/helpers/SauceLabsBrowserHelper.js, test/end-to-end/paths/jurisdictionConnections.js, test/end-to-end/saucelabs.conf.js
This change includes everything needed to get the crossbrowser tests running stably for Internet Explorer and Safari via Saucelabs:
- add latest Safari on latest Mac to crossbrowser test list
- move test setup out of `Before()` hook because Codecept doesn't retry these steps if there's a failure
- increase screen resolution for Safari and IE as the tests were more susceptible to being flakey on smaller browser windows (not related to the website functionality)
Fixes # 
https://tools.hmcts.net/jira/browse/TA-163
https://tools.hmcts.net/jira/browse/TA-185
Tests have been successfully running via the nightly pipeline
* Hardware:
* JDK:
=> Fix: Crossbrowser IE and Safari tests (v4)

test/end-to-end/paths/errorPaths.js
I think this was put in place as a temporary workaround. It seems reasonable to me that we don't see a cookie error page when trying to log in any environment.
Test was updated.
=> DIV-6673: Updating test to treat preview and non-preview URL equally

app.js
> chat.js:1 The source list for Content Security Policy directive 'frame-src' contains an invalid source: ''none''. It will be ignored. Note that 'none' has no effect unless it is the only expression in the source list.
Noticed in production logs in dynatrace and in my browser console
=> Remove invalid frame-src attribute in CSP

app/core/utils/respondentSolicitorSearchHelper.js, app/core/utils/respondentSolicitorSearchHelper.test.js, app/steps/respondent/correspondence/solicitor-search/content.json, app/steps/respondent/correspondence/solicitor-search/index.js, app/steps/respondent/correspondence/solicitor-search/index.test.js, app/views/common/components/respondentSolicitorComponents.html, test/end-to-end/pages/organisation-search/search.js
https://tools.hmcts.net/jira/browse/DIV-6760
Adds mandatory solicitor email to organisation lookup (currently only available in enter organisation manually)
=> DIV-6760: Solicitor email mandatory during organisation lookup

app/core/utils/respondentSolicitorSearchHelper.js, app/core/utils/respondentSolicitorSearchHelper.test.js, app/steps/respondent/correspondence/solicitor-search/index.js, app/steps/respondent/correspondence/solicitor-search/index.test.js, app/steps/respondent/correspondence/solicitor-search/partials/checkYourAnswersTemplate.html, app/steps/respondent/correspondence/use-home-address/index.js, app/steps/respondent/correspondence/use-home-address/index.test.js, app/steps/respondent/correspondence/use-home-address/partials/checkYourAnswersTemplate.html
https://tools.hmcts.net/jira/browse/DIV-6837
CYA views for both Use Home Address and Solicitor Search have been updated to reflect the current updates introduced by the Respondent Solicitor Search feature. Correct data is now displayed for the `Where should your <xxx> divorce papers be sent?` and `Enter details of your <xxx> solicitor`. All updates to the Use home address CYA display view is behind a feature toggle as well.
=> DIV-6837: Update check your answers page for respondent solicitor details

app/steps/respondent/correspondence/send-to-solicitor/content.json
On the https://petitioner-frontend-aks.aat.platform.hmcts.net/petitioner-respondent/correspondence/send-to-solicitor, for 'Where should your husband's/wife's divorce be sent?', rather than 
“I ba gyfeiriad y dylid anfon papurau ysgaru eich gŵr/gwraig?” we have 'I ble y dylid anfon eich gwraig papurau ysgariad?' which I think translates slightly differently.
=> DIV-6850-Add-new-question-in-Welsh

config/default.yaml, package.json, test/end-to-end/saucelabs.conf.js, yarn.lock
Bump superagent-proxy module (2.1.0 -> 3.0.0) to fix dependency check issue which asks to go to >=5.0.0 for pac-resolver dependency.
https://tools.hmcts.net/jira/browse/DFR-556
=> DFR-556 - Bump superagent-proxy 2.1.0 -> 3.0.0

Jenkinsfile_nightly
Change the build time to 3am, from 10pm
Fixes #DFR-1133 (issue)
The cross browser tests failing due to running out of sauce labs licenses
=> DFR-1133 Change nightly build time to 5am UTC
